### ISSUE TITLE
Blocking call to open inside the event loop

### ISSUE THREAD

**Issue by baget** [rt400/School-Vacation#6]
I'm running the latest  version

Core: 2024.6.4
Supervisor: 2024.06.2
OS: 12.4

Getting the following in the Log:

2024-07-03 19:00:40.211 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'school_holidays' at custom_components/school_holidays/sensor.py, line 124: with codecs.open(self.config_path + 'school_data.json', 'w', encoding='utf-8') as outfile: (offender: <frozen codecs>, line 918: ?), please report it to the author of the 'school_holidays' custom integration

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1289, in async_device_update
    await self.async_update()
  File "/config/custom_components/school_holidays/sensor.py", line 114, in async_update
    await self.create_db_file()
  File "/config/custom_components/school_holidays/sensor.py", line 124, in create_db_file
    with codecs.open(self.config_path + 'school_data.json', 'w', encoding='utf-8') as outfile:

**Comment by rt400** [comment]
Hi.
This is only a warning, not affect to the code...
But i already upload a fix to this warning.
Thanks for ley me know...
